/**
 * Builds the www/ bundle that the Android (Capacitor) app ships.
 *
 *   npm run build:www
 *   TA_API_BASE=https://my-own-deploy.example npm run build:www
 *
 * Copies the static app and rewrites js/app-config.js so the APK talks to
 * the cloud backend — the same accounts/settings/chat APIs as the web app,
 * which is what makes accounts interoperable between web and Android.
 * Local-only usage (test accounts, BYOK keys, local plans) needs no backend.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'www');
const API_BASE = (process.env.TA_API_BASE || 'https://time-architect-phi.vercel.app').replace(/\/+$/, '');

const COPIES = [
    'index.html',
    'manifest.webmanifest',
    'sw.js',
    'css/time-architect.css',
    'js/calendar-planner.js',
    'js/app-config.js',
    'icons/icon-192.png',
    'icons/icon-512.png',
    'icons/icon-maskable-512.png',
    'icons/apple-touch-icon.png'
];

fs.rmSync(OUT, { recursive: true, force: true });
for (const rel of COPIES) {
    const from = path.join(ROOT, rel);
    const to = path.join(OUT, rel);
    fs.mkdirSync(path.dirname(to), { recursive: true });
    fs.copyFileSync(from, to);
}

const appConfig = `/* Generated by scripts/build-www.mjs for the Android build. */
(function () {
    try {
        const stored = localStorage.getItem('ta_api_base_v1');
        if (stored) {
            window.TIME_ARCHITECT_API_BASE = String(stored).replace(/\\/+$/, '');
            return;
        }
    } catch (e) { /* storage unavailable */ }
    window.TIME_ARCHITECT_API_BASE = ${JSON.stringify(API_BASE)};
})();
`;
fs.writeFileSync(path.join(OUT, 'js/app-config.js'), appConfig);

console.log(`www/ built (${COPIES.length} files), API base: ${API_BASE}`);
